title = "Vijay Raja"
baseURL = "https://vijaywhat.github.io/"
theme = "resume-theme"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Coimbatore, India"
favicon = "/favicon.ico"
firstName = "Vijay"
lastName = "Raja"
phone = "1-555"
showSocializations = true
showContact = false
sections = ["skills","publications","blog","creations","contributions","experience","education"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/vijay-raja42/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/vijaywhat/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
